[colors.bright]
black = "#192537"
blue = "#366cd5"
cyan = "#48b3b6"
green = "#139062"
magenta = "#afafff"
red = "#ff5555"
white = "#b1c9e1"
yellow = "#f0c674"

[colors.normal]
black = "#141d2b"
blue = "#2c58ad"
cyan = "#388b8d"
green = "#0d6444"
magenta = "#af87ff"
red = "#b64b4b"
white = "#8b9db0"
yellow = "#af9155"

[colors.primary]
background = "#1d1e2a"
foreground = "#dddddd"

[colors.selection]
background = "#725e97"
text = "#ffffff"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Semibold"

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 16
y = 16
